language: go
sudo: true
go:
  - 1.11.x
  - tip

before_install:
  - cd
  - wget https://github.com/ImageMagick/ImageMagick6/archive/6.9.10-11.tar.gz
  - tar xvzf 6.9.10-11.tar.gz
  - cd ImageMagick*
  - ./configure --without-magick-plus-plus --without-perl --disable-openmp --with-gvc=no --disable-docs
  - make -j$(nproc)
  - make install
  - ldconfig /usr/local/lib
  - go get -t -v ./...

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
